### ISSUE TITLE
NTunes returns "Volumes" path prefix

### ISSUE THREAD

**Issue by jascott** [TooTallNate/nTunes#1]
Adapting NodeFloyd for my own purposes (thanks), I discovered that NTunes is returning the path with "/Volumes" prefix instead of in this case "/Users" which was causing ffmpeg to choke. MacOS 10.6.

**Comment by TooTallNate** [comment]
Yeah thanks for the report. This will be addressed in the upcoming `1.0` release of nTunes, which will use [NodObjC](https://github.com/TooTallNate/NodObjC) internally.

**Comment by edento** [comment]
Hey TooTallNate!
I know it has been a while now... but maybe you can help me with your package?
I have installed via npm:
`sudo npm install -g nTunes`

in my server.js (entry point) I have:
```
var port = process.env.PORT || 3000;
app.use(express.static(__dirname + '/public'));
app.listen(port);
console.log('Listening on port ' + port);
```
`var nTunes = require("nTunes");`

but then I receive the following error:

> Listening on port 3000
/Users/eden/..../my-project/node_modules/nTunes/nTunes.js:1
(function (exports, require, module, __filename, __dirname) { require.paths.unshift(__dirname);
                                                                           ^

> TypeError: Cannot read property 'unshift' of undefined
    at Object.<anonymous> (/Users/eden/Documents/Code/Web/chromecast-itunes/node_modules/nTunes/nTunes.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eden/..../my-project/server.js:14:14)
    at Module._compile (module.js:571:32)


Do you think you can help?

Thanks!
